sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '159357zjl123'
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: hdioqewhci
    access-key-secret: hsiuqwhui
    bucket-name: zqs132
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
